#!/usr/bin/env python3

import subprocess
import os
import magic


def main():
	EXCLUDE_DIRECTORIES = [".git"]

	shell_scripts = []

	root_directory = subprocess.check_output(
		["git", "rev-parse", "--show-toplevel"], text=True
	).strip()

	git_status_output = subprocess.check_output(
		["git", "status", "--porcelain"], text=True
	).strip()

	changed_files_relative = [
		i.split()[1] for i in git_status_output.split("\n") if i.split()[0] != "D"
	]

	changed_files = [os.path.join(root_directory, i) for i in changed_files_relative]

	for changed_file in changed_files:
		filetype = magic.detect_from_filename(changed_file).name

		if "shell" in filetype:
			shell_scripts.append(changed_file)

	if shell_scripts:
		subprocess.call(["shfmt", "-w", "-s"] + shell_scripts)

	subprocess.call(["git", "add", "-A"])


if __name__ == "__main__":
	main()
