#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config gapless_monocle true
bspc config single_monocle true

bspc rule -r '*'
bspc rule -a Chromium desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Zathura desktop='^3' state=tiled follow=on

~/.config/polybar/launch.sh

killall -q sxhkd feh compton unclutter

sxhkd &
compton -b -i 0.8 &
feh --bg-fill '/home/dundar/.dotfiles/.Misc/disco.png'
unclutter -idle 3.0 -root &
