#!/usr/bin/env python3

import argparse
import subprocess
import os
from pprint import pprint


def run(unparsed_arguments):
	arguments = unparsed_arguments.split()
	command = subprocess.check_output(arguments, universal_newlines=True)
	return command


parser = argparse.ArgumentParser()
parser.add_argument("accuracy")
args = parser.parse_args()

potential_duplicates = run("findimagedupes -R -q -t " + args.accuracy + " .")

for duplicateSet in potential_duplicates.strip().split("\n"):
	if not duplicateSet:
		continue
	current_folder = os.getcwd()
	duplicate_array = duplicateSet.split()
	pprint([i.replace(current_folder + "/", "") for i in duplicate_array])

	run("viewnior " + duplicateSet)
