#!/usr/bin/env python3

import argparse
import subprocess
from pprint import pprint


def run(arguments):
	return subprocess.check_output(arguments, text=True)


parser = argparse.ArgumentParser()
parser.add_argument("input_files", nargs="*")
args = parser.parse_args()

input_files = args.input_files

THRESHOLD = 0.1

videos = {}

for file in input_files:
	length = run(
		[
			"ffprobe",
			"-i",
			file,
			"-show_entries",
			"format=duration",
			"-v",
			"quiet",
			"-of",
			"csv=p=0",
		]
	).strip()
	videos[file] = length

length_video_tuples = []
for k, v in sorted(videos.items(), key=lambda item: item[1]):
	length_video_tuples.append((float(v), k))

potential_duplicates = [
	(length_video_tuples[i + 1][1], length_video_tuples[i][1])
	for i in range(len(length_video_tuples) - 1)
	if length_video_tuples[i + 1][0] - length_video_tuples[i][0] < THRESHOLD
]

pprint(potential_duplicates)
